### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hulksmaaash**
Softened some of the wording around the reason for the fork. ;-)

### CODE REVIEW

**Comment by hulksmaaash** [comment]
@markos FYI...in case notification did not show up.

**Comment by markos** [comment]
Ι merged #16, is it ok to close this one? Notification did arrive now with the mention, I think I need to work with github settings :)

**Comment by hulksmaaash** [comment]
This one is for master branch, but yes...ok to close. Thanks!

—
Robert "Robbie" Williamson
***@***.***>
Mobile: +1 737 932 3725
Sr Director, Solutions Engineering
Infrastructure - Arm<https://www.arm.com/solutions/infrastructure>

________________________________

**Comment by markos** [comment]
nevermind, thought it was a dupe for some reason, merged :)

**Pull request merged**
