### PR TITLE
Speed up truffle with 256b TBL instructions

### PR DESCRIPTION
**Pull request by ypicchi-arm**
256b wide SVE vectors allow some simplification of truffle. Up to 40% speedup on graviton3. Going from 12500 MB/s to 17000 MB/s on the microbenchmark.
SVE2 also offer this capability for 128b vector with a speedup around 25% compared to normal SVE

Add unit tests and benchmark for this wide variant

### CODE REVIEW

**Comment by ypicchi-arm** [comment]
Giving it one last check I just spotted some old code that crept into the commit. Don't merge it yet, I'll fix "dumpTruffleCharReach32" tomorrow.

**Comment by markos** [comment]
Unfortunately I couldn't even if I wanted to: https://buildbot-ci.vectorcamp.gr/#/changes/226

many failures even on Arm. If you want I can take a look and fix some of those.

**Comment by ypicchi-arm** [comment]
Ack. Don't worry, I'll look and fix those at the same time tomorrow. I tend to only test with gcc locally.

**Comment by ypicchi-arm** [comment]
The CI fail to pick up correctly my changes after the force push. I'll re-create the PR to have a clean run

**Pull request closed without merging**
