### PR TITLE
change FAT_RUNTIME to a normal option so it can be set to off

### LINKED ISSUE #89: building with clang for alpine fails on x86_64 and x86 with linking errors
I tried building with clang as gcc tunes too much for arm64 so it fails at runtime with rspamd.

When attempting to build with clang 12.0.1 it also has lots of nm errors for x86_86 and x86  finding glibc:

```
'libc.so.6': No such file
471nm: 'libc.so.6': No such file
```

Then at the end it has lots of linker errors, aarch64 compiles fine with clang.

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/611687

When using gcc 11.2.1 on arm64 (https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/605071/raw )is sets these:

```
-- gcc version 11.2.1
CMake Warning at CMakeLists.txt:185 (message):
  Something went wrong determining gcc tune:
  -mtune=armv8.2-a+crypto+fp16+rcpc+dotprod+ssbs not valid, falling back to
  -mtune=native
```
then further down
`-- Building for current host CPU: -march=armv8.2-a+crypto+fp16+rcpc+dotprod+ssbs -mtune=native`

So I have created a temporary patch:
https://gitlab.alpinelinux.org/alpine/aports/-/blob/1d08133a1b57f07565f7a679210c24db09681a32/community/vectorscan/armv8.patch

So I can build with gcc.

### PR DESCRIPTION
**Pull request by a16bitsysop**
fixes #89

### CODE REVIEW

**Comment by markos** [comment]
unfortunately, it fails to pass the tests in our CI:
https://jenkins.vectorcamp.gr/blue/organizations/jenkins/VectorCamp%2Fvectorscan-ci/detail/vectorscan-ci/74/pipeline
(there is a bug in blue ocean and direct URLs, if it fails please click open dashboard and select the PR)

**Comment by a16bitsysop** [comment]
Okay, looking at the build log it is titled clang build but GCC is being detected. Will have a look and see if I can find out where that's happening.

**Comment by a16bitsysop** [comment]
I checked the build logs when I tested it in the alpine ci and clang is detected there:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/638945#L199

But build fails as using busybox builtins and does not support ifunc anyway

**Comment by a16bitsysop** [comment]
It passes moving back to it's original location.

**Pull request merged**
